mongodb-university/Bluehawk

package.json, src/output.js
Minor tweaks for usability/out of the box correctness
=> Minor tweaks

src/builder.ts, src/codeGenerator.ts, src/fileHandler.ts, src/index.ts, src/test/fileHandler.test.ts, src/test/input/codeFile.js, src/test/input/stepFileWithCode.js
=> initial refactor of fileHandler to ts

src/constants.ts, src/output.ts
Simple port of constants, and (temporarily) quieting all output on the console.
=> Np constants

package-lock.json, package.json, src/bluehawk/Document.test.ts, src/bluehawk/Document.ts
- Similar to the deprecated MagicString.locate() function
- Useful for emphasize command
=> Add Document.getNewLocationFor(oldLocation)

src/bluehawk/parser/RootParser.ts, src/bluehawk/parser/parser.test.ts
- Many files don't end with newline, and Bluehawk should be ok with this
=> Accept files that do not end with newline

src/bluehawk/bluehawk.test.ts, src/bluehawk/bluehawk.ts, src/bluehawk/commands/emphasizeCommand.test.ts, src/bluehawk/commands/removeCommand.test.ts, src/bluehawk/commands/removeMetaRange.test.ts, src/bluehawk/commands/replaceCommand.test.ts, src/bluehawk/commands/snippetCommand.test.ts, src/bluehawk/commands/stateCommand.test.ts, src/bluehawk/commands/uncommentCommand.test.ts, src/bluehawk/getBluehawk.ts, src/bluehawk/parseAndProcess.ts, src/bluehawk/parser/LanguageSpecification.ts, src/bluehawk/parser/ParseResult.ts, src/bluehawk/parser/ParserStore.test.ts, src/bluehawk/parser/ParserStore.ts, src/bluehawk/parser/RootParser.ts, src/bluehawk/parser/index.ts, src/bluehawk/parser/lexer/makeBlockCommentTokens.ts, src/bluehawk/parser/lexer/makeLineCommentToken.ts, src/bluehawk/parser/lexer/makeStringLiteralToken.ts, src/bluehawk/parser/lexer/tokens.ts, src/bluehawk/parser/makeParser.ts, src/bluehawk/parser/visitor/index.ts, src/bluehawk/processor/Processor.test.ts, src/cli/commands/snip.ts
- Enhance language (comments, strings, file extensions) support
=> Language support

src/bluehawk/commands/SnippetCommand.ts, src/cli/commands/snip.test.ts
- I was "smart" and accounted for carriage returns (`\r\n`) but then
only allowed for 1 character-length newlines when dedenting
=> Fix carriage return handling in dedent

CONTRIBUTING.md, README.md
See a preview of the new readme at https://github.com/nathan-contino-mongo/Bluehawk-1/tree/improved-documentation
=> Onboarding Guide, Examples

README.md, src/cli/commands/snip.test.ts, src/cli/commands/snip.ts, src/cli/options.ts
sphynx-rst -> rst, requires arg, throws error if you don't provide valid lang
=> Spyphnx RST tpyo fxi

package-lock.json, package.json, src/bluehawk/bluehawk.ts, src/cli/commands/copy.test.ts, src/cli/commands/copy.ts
- Waiting for https://github.com/bevry/istextorbinary/pull/201
- Meanwhile, replace with a different library to do the same thing
=> Node 16 support: replace isbinaryortext with isbinaryfile

src/cli/commands/copy.ts, src/cli/commands/snip.test.ts, src/cli/commands/snip.ts, src/cli/main.ts
- snip and copy andlers return errors. If error list is not empty, exit with error code.
- Bluehawk check already did exit(1) on error
=> Actually exit(1) in cli on errors

src/cli/commands/copy.test.ts, src/cli/commands/copy.ts
Addresses https://github.com/mongodb-university/Bluehawk/issues/65
=> Copy permissions when copying files

README.md
Give folks who visit the Bluehawk repository another way to learn more about using Bluehawk in various workflows.
=> Add videos to README

src/bluehawk/parser/RootParser.ts, src/bluehawk/parser/lexer/makeLexer.ts, src/bluehawk/parser/parser.test.ts, src/bluehawk/parser/visitor/makeCstVisitor.ts, src/cli/commands/snip.test.ts
Add special case for block comments that behave like line comments.
=> Allow for block comments that behave like line comments (fix html comments)

src/bluehawk/getBluehawk.ts
This PR adds support for [UXML](https://docs.unity3d.com/Manual/UIE-UXML.html)
=> Add unity support with uxml files for addLanguage()

package-lock.json, src/bluehawk/Plugin.ts, src/bluehawk/index.ts, src/cli/cli.ts, src/cli/commandModules/list.ts
Fix build error with git plugin
=> Move "Plugin" to main library

docs/docusaurus.config.js
See https://docusaurus.io/docs/markdown-features/code-blocks#supported-languages
=> Add syntax highlighting for Java & Swift

src/bluehawk/getBluehawk.ts
=> Add Go as Supported Language

.github/workflows/deploy-docs.yaml, .github/workflows/node.js.yml, .github/workflows/test-deploy-docs.yaml, package-lock.json, package.json, src/bluehawk/parser/parser.test.ts, src/bluehawk/parser/visitor/jsonAttributeList.test.ts
Note: these changes make it so you must run the tests with Node v20
=> Fix vulns with npm audit fix

package-lock.json
Fixes a critical security vulnerability.
Also, @cbush, I had to revert some of the test changes you made in #144. Did the tests throw different expected errors for you?
=> Fix security vulnerability with npm audit fix
