.eslintrc.js, src/fileHandler.ts
A few small improvements and switching to typescript (not fully, but on the way).
The crux of the issue was the way file name and directory name were being derived. It was
```js
const fileparts = source.split("/");
const file = fileparts.pop();
const directory = fileparts.join("/")
```
and is now
```ts
const directory = path.dirname(source);
const file = path.basename(source);
```
This was okay if you specified a source other than the local directory, but if operating on a file from the current directory it would result in an empty string. Thus, "/output" was the only thing in the file path.
=> Directory improvements

package-lock.json, package.json, src/fileHandler.ts, src/index.ts
A bit of cleanup. While adding typescript goodies I noticed eslint was breaking. Turns out typescript 4 changed their ast a bit, so I had to bump from version 2 to version 4 on the eslint plugin.
=> code cleanup and dependency bump

src/getCodeBlocks.ts, src/test/getCodeBlocks.test.ts, tsconfig.json
This sets the lib to es2020, allowing all the latest hotness.
In addition, it refactors `getCodeBlock.js` to typescript. It removes some logic errors that were identified, and also removes the props parsing logic.
This logic should be handled by the new parser rather than overloading this command implementation.
=> Refactor get code block

src/BluehawkSource.ts, src/bluehawk.ts, src/fs/parseSource.ts, src/index.ts, src/parser/makeCstVisitor.ts, src/parser/validator.ts, src/processors/Processor.ts, src/processors/SnippetCommand.ts, src/processors/StateCommand.ts, src/processors/removeCommand.test.ts, src/processors/snippetCommand.test.ts, src/processors/stateCommand.test.ts, src/processors/uncommentCommand.test.ts, src/test/bluehawk.test.ts, src/test/jsonAttributeList.test.ts, src/test/multilang.test.ts, src/test/validator.test.ts, src/test/visitor.test.ts
- Add "--snippets" flag to cli to output snippets at destination
- Refactor BluehawkSource
- Fix slice -> snip
- Fix line command validator
- Support dedent on realistic codeblocks (not fully indented on blank lines)
- Protect against mismatch start/end tags
- Report errors on cli
=> Support end-to-end snippets test

src/BluehawkSource.ts, src/fs/parseSource.ts, src/index.ts, src/processors/Processor.ts, src/processors/SnippetCommand.ts, src/processors/StateCommand.ts, src/processors/removeCommand.test.ts, src/processors/snippetCommand.test.ts, src/processors/stateCommand.test.ts
Below are some examples of changes when running on realm tutorial codebase. Note that the changes are basically whitespace and newlines at end of file:
Generate tutorial snippets:
```shell
$ bluehawk -s swift-ios/ -d ~/docs/docs-realm/source/tutorial/generated/code/final  --state final --snippets
$ git diff
```
Generate tutorial repo branch:
```shell
$ bluehawk -s swift-ios/ -d ~/tutorial/realm-tutorial-ios-swift --state start
$ git diff
```
=> Support state output

package-lock.json, package.json, src/fs/parseSource.ts, src/index.ts
Original implementation would heedlessly open binary files and save them as text files. This fixes that by providing a special handler for binary files, which in this case just copies them directly.
=> Handle binary file copy

jest.config.js
- Something changed where the uncovered line reporting was reporting js instead of ts lines
- This restores it so that ts lines are used in coverage
=> Fix coverage to use ts output

src/bluehawk.ts, src/commands/Command.ts, src/commands/SnippetCommand.ts, src/commands/StateCommand.ts, src/commands/removeCommand.test.ts, src/commands/snippetCommand.test.ts, src/commands/stateCommand.test.ts, src/commands/uncommentCommand.test.ts, src/index.ts, src/io/parseSource.ts, src/processor/Processor.test.ts, src/processor/Processor.ts
- Adds support for async commands and listeners
- Per Nathan's idea of eventually having commands or listeners that could do something with HTTP
- Minor refactor to processor required. Most changes are to update tests to use async interface.
=> Async commands & listeners

package-lock.json, package.json, src/bluehawk.ts, src/commands/Command.ts, src/commands/ReplaceCommand.ts, src/commands/SnippetCommand.ts, src/commands/StateCommand.ts, src/commands/UncommentCommand.ts, src/commands/removeMetaRange.ts, src/commands/replaceCommand.test.ts, src/index.ts, src/io/messageHandler.ts, src/io/parseSource.ts, src/parser/CommandNode.ts, src/parser/ParseResult.ts, src/parser/RootParser.ts, src/parser/lexer/makeBlockCommentTokens.ts, src/parser/lexer/makePayloadPattern.ts, src/parser/lexer/tokenCategoryFilter.ts, src/parser/parser.test.ts, src/parser/visitor/jsonAttributeList.test.ts, src/parser/visitor/makeCstVisitor.ts, src/parser/visitor/multilang.test.ts, src/parser/visitor/visitor.test.ts, src/processor/Processor.ts, src/processor/makeAttributesConformToJsonSchemaRule.test.ts, src/processor/makeAttributesConformToJsonSchemaRule.ts, src/processor/validator.ts, tsconfig.json
- Implements attribute schema conformity checker. This allows you to define validator rules that check that the attribute block after a command actually matches a given JSON schema.
- JSON schema library AJV requires strict null checking for nice typescript features, so enabled that -- resulting in lots of conflicts with Chevrotain nullability
- Enabled TypeScript strict mode while we're at it
- Implements "replace", which takes a record of search terms to replace terms and replaces all in the block.
- Fixes a bug in attribute lists where comments were not stripped from inner JSON objects.
=> Schema conform, TypeScript strict mode, and Replace command

README.md, src/index.ts, src/io/parseSource.ts
You can add commands and listeners by creating a JS file (or node project) that implements the register() function.
```js
// plugin.js
exports.register = (bluehawk) => {
bluehawk.registerCommand("my-command", {
rules: [],
process: (request) => {
console.log("gotcha")
}
});
};
```
Usage:
```shell
bluehawk --plugin ./plugin --source source.txt
```
You can pass the `--plugin` flag multiple times to load different plugins.
This is a rudimentary first pass. Error handling could be improved, and it might be nice to allow users to register binary file listeners.
=> Implement basic plugin system

src/commands/SnippetCommand.ts, src/commands/replaceCommand.test.ts
- Dedent would remove at the wrong index after a replace command in the snippets
- This uses the original string to get the correct indexes
=> Fix interop of Replace + snippet dedent

package-lock.json, package.json, src/bluehawk/parser/visitor/makeCstVisitor.ts
- Upgrade Chevrotain
- Chevrotain visitor validation required corresponding grammar rules
for all methods.
- Despite allowing $ names locally as helpers on chevrotain 7.0, it seems this triggered the
error in 7.1:
Error: Errors Detected in CST Visitor :
Redundant visitor method: <$visit> on CstVisitor CST Visitor
There is no Grammar Rule corresponding to this method's name.
at CstVisitor.validateVisitor (/usr/local/lib/node_modules/bluehawk/node_modules/chevrotain/lib/src/parse/cst/cst_visitor.js:49:23)
at new CstVisitor (/usr/local/lib/node_modules/bluehawk/build/bluehawk/parser/visitor/makeCstVisitor.js:109:19)
at Object.makeCstVisitor (/usr/local/lib/node_modules/bluehawk/build/bluehawk/parser/visitor/makeCstVisitor.js:102:12)
at Bluehawk.parse …
=> Update visitor for updated Chevrotain visitor validator

src/bluehawk/parser/RootParser.ts, src/bluehawk/parser/extractCommandNamesFromTokens.ts, src/bluehawk/parser/locationFromToken.ts, src/bluehawk/parser/visitor/makeCstVisitor.ts, src/bluehawk/parser/visitor/visitor.test.ts
- In the case of nested commands, a mismatched command end name could result in a different parser error when the parser encounters EOF, because the mismatched end name closes the inner but the outer never gets closed. This means the visitor can't report the error accurately because it never gets past the parser stage for the visitor to see.
- Solution is to add a private channel of Bluehawk errors in the parser that can detect things like this.
For example:
```cs
// :code-block-start: transaction
// :replace-start: {
//  "terms": {
//   "WritePerson": "Person",
//   "WriteDog" : "Dog" }
// }
realm.Write(() =>
{
// Create someone to take care of ssome dogs.
var ali = new WritePerson { Id = 1, Name = "Ali" };
realm.Add(ali);
// Find dogs younger than 2.
var puppies = …
```
=> Detect mismatched command names earlier in parser

.release-it.json, package-lock.json, package.json
Adds [release-it](https://www.npmjs.com/package/release-it#git) and `npm run release` script for convenient release, versioning, and tagging.
This uses GitHub releases which requires a token as an environment variable if you want to release. See https://github.com/release-it/release-it/blob/master/docs/github-releases.md
=> Add release-it for release management

src/bluehawk/bluehawk.test.ts, src/bluehawk/bluehawk.ts, src/bluehawk/commands/Command.ts, src/bluehawk/commands/RemoveCommand.ts, src/bluehawk/commands/ReplaceCommand.ts, src/bluehawk/commands/SnippetCommand.ts, src/bluehawk/commands/StateCommand.ts, src/bluehawk/commands/UncommentCommand.ts, src/bluehawk/commands/removeCommand.test.ts, src/bluehawk/commands/replaceCommand.test.ts, src/bluehawk/getBluehawk.ts, src/bluehawk/parser/CommandNode.ts, src/bluehawk/parser/ParseResult.ts, src/bluehawk/parser/index.ts, src/bluehawk/parser/visitor/makeCstVisitor.ts, src/bluehawk/processor/Processor.test.ts, src/bluehawk/processor/Processor.ts, src/bluehawk/processor/makeAttributesConformToJsonSchemaRule.test.ts, src/bluehawk/processor/makeAttributesConformToJsonSchemaRule.ts, src/bluehawk/processor/validator.test.ts, src/bluehawk/processor/validator.ts
Really, all that was needed here was a unit test to prove that :remove: can be used as a line command. But there was lacking protection and developer ergonomics around line vs. block command. In particular, someone could use any command name as either a line or block command and there would have to be protection against that built into each command, instead of checked at the validator.
This PR cleans up various odds and ends as well.
- Bake in the difference between commands that support line mode, block mode, or both modes.
- Make a helper function to reduce boilerplate and enhance auto-complete support for filling out command implementations.
- Validate in both the validator and in the processor that a given command appears in a mode that the command processor can actually handle.
- …
=> `Remove` as line command & line command distinction refactor

src/bluehawk/bluehawk.test.ts, src/bluehawk/bluehawk.ts, src/bluehawk/commands/Command.ts, src/bluehawk/commands/RemoveCommand.ts, src/bluehawk/commands/ReplaceCommand.ts, src/bluehawk/commands/SnippetCommand.ts, src/bluehawk/commands/StateCommand.ts, src/bluehawk/commands/UncommentCommand.ts, src/bluehawk/commands/removeCommand.test.ts, src/bluehawk/commands/replaceCommand.test.ts, src/bluehawk/commands/snippetCommand.test.ts, src/bluehawk/commands/stateCommand.test.ts, src/bluehawk/commands/uncommentCommand.test.ts, src/bluehawk/getBluehawk.ts, src/bluehawk/parseAndProcess.ts, src/bluehawk/processor/Processor.test.ts, src/bluehawk/processor/Processor.ts, src/bluehawk/processor/validator.test.ts
- Add convenience constructor to Bluehawk
- Still allow alias names for commands
=> Refactor Command to include its name

src/bluehawk/commands/UncommentCommand.ts, src/bluehawk/commands/uncommentCommand.test.ts
- "Uncomment" should only remove a layer of comments at the start of a line (give or take any whitespace)
- Add supporting unit tests to verify
=> Fix uncomment command's overeager comment removal

src/bluehawk/commands/SnippetCommand.ts, src/bluehawk/commands/snippetCommand.test.ts
- Don't generate redundant snippet-nested files
- Add unit test
=> Explicitly support nested snippets

src/bluehawk/parser/RootParser.ts
- By using 'blockComment' instead of 'BlockCommentStart' when nesting is allowed,
nested comments would require a nested closing block comment token. This isn't
how any languages I know of actually work - additional BlockCommentStarts should
be ignored.
=> Fix nested code block in parser

package.json, src/bluehawk/bluehawk.ts, src/bluehawk/getBluehawk.ts, src/cli/Plugin.ts, src/cli/cli.ts, src/cli/commands/check.ts, src/cli/commands/copy.ts, src/cli/commands/index.ts, src/cli/commands/list/commands.ts, src/cli/commands/list/index.ts, src/cli/commands/list/states.ts, src/cli/commands/snip.ts, src/cli/index.ts, src/cli/options.ts, src/index.ts
- Load plugins before anything else in CLI
- Give plugins the opportunity to modify CLI itself (via Yargs)
- Pass bluehawk and yargs versions to plugins in case of version drift
=> Update plugin architecture

src/bluehawk/bluehawk.ts, src/bluehawk/project/loadProjectPaths.test.ts, src/bluehawk/project/loadProjectPaths.ts
It seems that passing `ignore.ignores()` an empty string causes... problems (crashes entire program silently, swallowing error message)
=> actually process explicit files passed in

src/bluehawk/getBluehawk.ts
Quash the warning "overriding language specification for extension 'uxml'" - note uxml is still below in XML-likes
=> Remove duplicate language extension spec

.github/workflows/deploy-docs.yaml, .github/workflows/test-deploy-docs.yaml
fix issue where api docs not building b/c they don't have npm dependencies.
=> patch: add install bluehawk scripts to ci

src/cli/cli.ts, src/cli/commandModules/list.ts
- Since moving the commandDir() function, relative paths were broken
=> Use absolute paths to locate commandModules

src/bluehawk/actions/snip.test.ts, src/bluehawk/getBluehawk.ts, src/bluehawk/parser/lexer/tokens.ts
Want to test bluehawk for CSFLE sample projects so trying to get in minimal python support.
This adds supports for string literals of the following form:
"\<some single line string with escaped double quotes\>"
'\<some single line string with escaped single quotes\>'
'''\<some multiline string with escaped single quotes\>'''
"""\<some multiline string with escaped double quotes\>"""
=> Add Python as Supported Language

package-lock.json, package.json, src/bluehawk/actions/ActionReporter.ts, src/bluehawk/index.ts, src/cli/cli.ts
- Updates yargs to ^17
- Switches the `ActionReporter.errorCount` getter to be a readonly property
- Exports `ActionReporter` and `ConsoleActionReporter` for plugin use
=> Update for Bluehawk 1.0 plugins

docs/docs/reference/cli.md, docs/docs/reference/tags.md, src/bluehawk/actions/snip.test.ts, src/bluehawk/actions/snip.ts
new `md` output for `--format`.
output is formatted in a markdown codeblock, such as 
````md
```js
const foo = 'bar';
```
````
note: doesn't support line highlighting
addresses https://github.com/mongodb-university/Bluehawk/issues/112
=> Markdown formatted output

docs/docs/use-cases.md
A code sample on [this page](https://mongodb-university.github.io/Bluehawk/use-cases) uses :state-uncomment-end: when it appears :state-end: should be used.
=> remove "uncomment" from state-end

src/bluehawk/actions/snip.test.ts, src/bluehawk/actions/snip.ts
This PR creates only the formatted files when running the snip command with a format specified.
Previously, in Bluehawk 1.3.1 if we run the following command: 
`bluehawk snip __tests__/ts/CRUD/delete-test.tsx -o outputfolder --format=rst` 
this will produce 2 files:
```
├── delete-test.snippet.crud-delete-object.tsx
└── delete-test.snippet.crud-delete-object.tsx.rst
```
With this PR, it produces only:
```
└── delete-test.snippet.crud-delete-object.tsx.rst
```
since the format specified is "rst" (i.e it should not produce the 'tsx' file.)
=> Generate only formatted files when using '--format' flag

src/bluehawk/actions/snip.ts
Extending the nasty `rstLanguageMap` hack so that I create `.rst`-formatted samples for React Native.
Looks like a test failed - but I didn't touch that. Something to look into later?
```
Test failed: ./logLevel
Compare ./logLevel/expected and ./logLevel/output to debug.
```
=> Add .jsx and .tsx to rstLanguageMap

.github/workflows/node.js.yml, integrationTests/snip/expected/sample.snippet.cpp-test.cpp, integrationTests/snip/expected/sample.snippet.failing-cpp-test.cpp, integrationTests/snip/input/sample.cpp, src/bluehawk/parser/lexer/lexer.test.ts, src/bluehawk/parser/lexer/tokens.ts, src/bluehawk/parser/visitor/jsonAttributeList.test.ts
Closes #145 
This adds regex to avoid matching Bluehawk tags surrounded by `::` - it should only match tags with a single `:` surrounding them. This resolves C++ syntax issues, as C++ uses `::` to reference class members.
Added a test - with the old patterns, it fails as expected, but with the new patterns, the integration test runs.
This also coincidentally fixes 1 of the failing tests reported in #149.
Upon initially adding the new regex, I got a few warnings from Chevrotain which Bluehawk reported as Errors. First was `Unable to identify line terminator usage in pattern`, detailed in the Chevrotain docs here: https://chevrotain.io/docs/guide/resolving_lexer_errors.html#IDENTIFY_TERMINATOR
Adding `line_breaks: false,` resolved this warning/error.
Then I got `Failed parsing < /.../ > …
=> Fix C++ syntax collision
